// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tMITE_h___
#include "tMITE.h"

#endif

tMITE::tMITE(tBusSpaceReference addrSpace, nMDBG::tStatus2* s)

{
   if (s && s->isFatal()) return;

   _addressOffset = 0;
   _addrSpace = addrSpace;
   _deallocateBus = kFalse;
   _initialize(s);
}


void tMITE::reset(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   ChannelOperation.setRegister(0x0, s);
   ChannelControl.setRegister(0x0, s);
   ChannelStatus.setRegister(0x0, s);
   BaseCount.setRegister(0x0, s);
   TransferCount.setRegister(0x0, s);
   FifoCount.setRegister(0x0, s);
   MemoryConfig.setRegister(0x0, s);
   DeviceConfig.setRegister(0x0, s);
   BaseAddress.setRegister(0x0, s);
   MemoryAddress.setRegister(0x0, s);
   DeviceAddress.setRegister(0x0, s);
}

void tMITE::_initialize(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   //----------------------------------------
   // set register maps of all registers
   //----------------------------------------
   ChannelOperation.setRegisterMap(this);
   ChannelControl.setRegisterMap(this);
   ChannelStatus.setRegisterMap(this);
   BaseCount.setRegisterMap(this);
   TransferCount.setRegisterMap(this);
   FifoCount.setRegisterMap(this);
   MemoryConfig.setRegisterMap(this);
   DeviceConfig.setRegisterMap(this);
   BaseAddress.setRegisterMap(this);
   MemoryAddress.setRegisterMap(this);
   DeviceAddress.setRegisterMap(this);

   reset(s);
}

tMITE::~tMITE()
{
}



// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

