// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___t6723_h___
#include "t6723.h"

#endif

t6723::t6723(tBusSpaceReference addrSpace, nMDBG::tStatus2* s)
 : DirectData_00(0x80,0xf),
   DirectData_01(0x82,0x10),
   DirectData_02(0x84,0x11),
   DirectData_03(0x86,0x12),
   DirectData_04(0x88,0x13),
   DirectData_05(0x8a,0x14),
   DirectData_06(0x8c,0x15),
   DirectData_07(0x8e,0x16),
   DirectData_08(0x90,0x17),
   DirectData_09(0x92,0x18),
   DirectData_10(0x94,0x19),
   DirectData_11(0x96,0x1a),
   DirectData_12(0x98,0x1b),
   DirectData_13(0x9a,0x1c),
   DirectData_14(0x9c,0x1d),
   DirectData_15(0x9e,0x1e),
   DirectData_16(0xa0,0x1f),
   DirectData_17(0xa2,0x20),
   DirectData_18(0xa4,0x21),
   DirectData_19(0xa6,0x22),
   DirectData_20(0xa8,0x23),
   DirectData_21(0xaa,0x24),
   DirectData_22(0xac,0x25),
   DirectData_23(0xae,0x26),
   DirectData_24(0xb0,0x27),
   DirectData_25(0xb2,0x28),
   DirectData_26(0xb4,0x29),
   DirectData_27(0xb6,0x2a),
   DirectData_28(0xb8,0x2b),
   DirectData_29(0xba,0x2c),
   DirectData_30(0xbc,0x2d),
   DirectData_31(0xbe,0x2e),
   Calibration_00(0x100,0x2f),
   Calibration_01(0x104,0x30),
   Calibration_02(0x108,0x31),
   Calibration_03(0x10c,0x32),
   Calibration_04(0x110,0x33),
   Calibration_05(0x114,0x34),
   Calibration_06(0x118,0x35),
   Calibration_07(0x11c,0x36),
   Calibration_08(0x120,0x37),
   Calibration_09(0x124,0x38),
   Calibration_10(0x128,0x39),
   Calibration_11(0x12c,0x3a),
   Calibration_12(0x130,0x3b),
   Calibration_13(0x134,0x3c),
   Calibration_14(0x138,0x3d),
   Calibration_15(0x13c,0x3e),
   Calibration_16(0x140,0x3f),
   Calibration_17(0x144,0x40),
   Calibration_18(0x148,0x41),
   Calibration_19(0x14c,0x42),
   Calibration_20(0x150,0x43),
   Calibration_21(0x154,0x44),
   Calibration_22(0x158,0x45),
   Calibration_23(0x15c,0x46),
   Calibration_24(0x160,0x47),
   Calibration_25(0x164,0x48),
   Calibration_26(0x168,0x49),
   Calibration_27(0x16c,0x4a),
   Calibration_28(0x170,0x4b),
   Calibration_29(0x174,0x4c),
   Calibration_30(0x178,0x4d),
   Calibration_31(0x17c,0x4e),
   LastWrite_00_0(0x200,0x4f),
   LastWrite_00_1(0x202,0x50),
   LastWrite_01_0(0x204,0x51),
   LastWrite_01_1(0x206,0x52),
   LastWrite_02_0(0x208,0x53),
   LastWrite_02_1(0x20a,0x54),
   LastWrite_03_0(0x20c,0x55),
   LastWrite_03_1(0x20e,0x56),
   LastWrite_04_0(0x210,0x57),
   LastWrite_04_1(0x212,0x58),
   LastWrite_05_0(0x214,0x59),
   LastWrite_05_1(0x216,0x5a),
   LastWrite_06_0(0x218,0x5b),
   LastWrite_06_1(0x21a,0x5c),
   LastWrite_07_0(0x21c,0x5d),
   LastWrite_07_1(0x21e,0x5e),
   LastWrite_08_0(0x220,0x5f),
   LastWrite_08_1(0x222,0x60),
   LastWrite_09_0(0x224,0x61),
   LastWrite_09_1(0x226,0x62),
   LastWrite_10_0(0x228,0x63),
   LastWrite_10_1(0x22a,0x64),
   LastWrite_11_0(0x22c,0x65),
   LastWrite_11_1(0x22e,0x66),
   LastWrite_12_0(0x230,0x67),
   LastWrite_12_1(0x232,0x68),
   LastWrite_13_0(0x234,0x69),
   LastWrite_13_1(0x236,0x6a),
   LastWrite_14_0(0x238,0x6b),
   LastWrite_14_1(0x23a,0x6c),
   LastWrite_15_0(0x23c,0x6d),
   LastWrite_15_1(0x23e,0x6e),
   LastWrite_16_0(0x240,0x6f),
   LastWrite_16_1(0x242,0x70),
   LastWrite_17_0(0x244,0x71),
   LastWrite_17_1(0x246,0x72),
   LastWrite_18_0(0x248,0x73),
   LastWrite_18_1(0x24a,0x74),
   LastWrite_19_0(0x24c,0x75),
   LastWrite_19_1(0x24e,0x76),
   LastWrite_20_0(0x250,0x77),
   LastWrite_20_1(0x252,0x78),
   LastWrite_21_0(0x254,0x79),
   LastWrite_21_1(0x256,0x7a),
   LastWrite_22_0(0x258,0x7b),
   LastWrite_22_1(0x25a,0x7c),
   LastWrite_23_0(0x25c,0x7d),
   LastWrite_23_1(0x25e,0x7e),
   LastWrite_24_0(0x260,0x7f),
   LastWrite_24_1(0x262,0x80),
   LastWrite_25_0(0x264,0x81),
   LastWrite_25_1(0x266,0x82),
   LastWrite_26_0(0x268,0x83),
   LastWrite_26_1(0x26a,0x84),
   LastWrite_27_0(0x26c,0x85),
   LastWrite_27_1(0x26e,0x86),
   LastWrite_28_0(0x270,0x87),
   LastWrite_28_1(0x272,0x88),
   LastWrite_29_0(0x274,0x89),
   LastWrite_29_1(0x276,0x8a),
   LastWrite_30_0(0x278,0x8b),
   LastWrite_30_1(0x27a,0x8c),
   LastWrite_31_0(0x27c,0x8d),
   LastWrite_31_1(0x27e,0x8e)
{
   if (s && s->isFatal()) return;

   _addressOffset = 0;
   _addrSpace = addrSpace;
   _deallocateBus = kFalse;
   _initialize(s);
}

void t6723::reset(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   SerialCommand.setRegister(0x0, s);
   Initialization.setRegister(0x0, s);
   StatusReg.setRegister(0x0, s);
   AOCalChanSel.setRegister(0x0, s);
   ADCCommand.setRegister(0x0, s);
   ADCStatus.setRegister(0x0, s);
   ADCConversionData16.setRegister(0x0, s);
   AOMisc.setRegister(0x0, s);
   AOChanCount.setRegister(0x0, s);
   DACFIFOFlags.setRegister(0x0, s);
   FIFOData.setRegister(0x0, s);
   DACDirty.setRegister(0x0, s);
   DACLastWriteBank.setRegister(0x0, s);
   FPGAVersion.setRegister(0x0, s);
   FPGACheck.setRegister(0x0, s);
   DirectData_00.setRegister(0x0, s);
   DirectData_01.setRegister(0x0, s);
   DirectData_02.setRegister(0x0, s);
   DirectData_03.setRegister(0x0, s);
   DirectData_04.setRegister(0x0, s);
   DirectData_05.setRegister(0x0, s);
   DirectData_06.setRegister(0x0, s);
   DirectData_07.setRegister(0x0, s);
   DirectData_08.setRegister(0x0, s);
   DirectData_09.setRegister(0x0, s);
   DirectData_10.setRegister(0x0, s);
   DirectData_11.setRegister(0x0, s);
   DirectData_12.setRegister(0x0, s);
   DirectData_13.setRegister(0x0, s);
   DirectData_14.setRegister(0x0, s);
   DirectData_15.setRegister(0x0, s);
   DirectData_16.setRegister(0x0, s);
   DirectData_17.setRegister(0x0, s);
   DirectData_18.setRegister(0x0, s);
   DirectData_19.setRegister(0x0, s);
   DirectData_20.setRegister(0x0, s);
   DirectData_21.setRegister(0x0, s);
   DirectData_22.setRegister(0x0, s);
   DirectData_23.setRegister(0x0, s);
   DirectData_24.setRegister(0x0, s);
   DirectData_25.setRegister(0x0, s);
   DirectData_26.setRegister(0x0, s);
   DirectData_27.setRegister(0x0, s);
   DirectData_28.setRegister(0x0, s);
   DirectData_29.setRegister(0x0, s);
   DirectData_30.setRegister(0x0, s);
   DirectData_31.setRegister(0x0, s);
   Calibration_00.setRegister(0x0, s);
   Calibration_01.setRegister(0x0, s);
   Calibration_02.setRegister(0x0, s);
   Calibration_03.setRegister(0x0, s);
   Calibration_04.setRegister(0x0, s);
   Calibration_05.setRegister(0x0, s);
   Calibration_06.setRegister(0x0, s);
   Calibration_07.setRegister(0x0, s);
   Calibration_08.setRegister(0x0, s);
   Calibration_09.setRegister(0x0, s);
   Calibration_10.setRegister(0x0, s);
   Calibration_11.setRegister(0x0, s);
   Calibration_12.setRegister(0x0, s);
   Calibration_13.setRegister(0x0, s);
   Calibration_14.setRegister(0x0, s);
   Calibration_15.setRegister(0x0, s);
   Calibration_16.setRegister(0x0, s);
   Calibration_17.setRegister(0x0, s);
   Calibration_18.setRegister(0x0, s);
   Calibration_19.setRegister(0x0, s);
   Calibration_20.setRegister(0x0, s);
   Calibration_21.setRegister(0x0, s);
   Calibration_22.setRegister(0x0, s);
   Calibration_23.setRegister(0x0, s);
   Calibration_24.setRegister(0x0, s);
   Calibration_25.setRegister(0x0, s);
   Calibration_26.setRegister(0x0, s);
   Calibration_27.setRegister(0x0, s);
   Calibration_28.setRegister(0x0, s);
   Calibration_29.setRegister(0x0, s);
   Calibration_30.setRegister(0x0, s);
   Calibration_31.setRegister(0x0, s);
   LastWrite_00_0.setRegister(0x0, s);
   LastWrite_00_1.setRegister(0x0, s);
   LastWrite_01_0.setRegister(0x0, s);
   LastWrite_01_1.setRegister(0x0, s);
   LastWrite_02_0.setRegister(0x0, s);
   LastWrite_02_1.setRegister(0x0, s);
   LastWrite_03_0.setRegister(0x0, s);
   LastWrite_03_1.setRegister(0x0, s);
   LastWrite_04_0.setRegister(0x0, s);
   LastWrite_04_1.setRegister(0x0, s);
   LastWrite_05_0.setRegister(0x0, s);
   LastWrite_05_1.setRegister(0x0, s);
   LastWrite_06_0.setRegister(0x0, s);
   LastWrite_06_1.setRegister(0x0, s);
   LastWrite_07_0.setRegister(0x0, s);
   LastWrite_07_1.setRegister(0x0, s);
   LastWrite_08_0.setRegister(0x0, s);
   LastWrite_08_1.setRegister(0x0, s);
   LastWrite_09_0.setRegister(0x0, s);
   LastWrite_09_1.setRegister(0x0, s);
   LastWrite_10_0.setRegister(0x0, s);
   LastWrite_10_1.setRegister(0x0, s);
   LastWrite_11_0.setRegister(0x0, s);
   LastWrite_11_1.setRegister(0x0, s);
   LastWrite_12_0.setRegister(0x0, s);
   LastWrite_12_1.setRegister(0x0, s);
   LastWrite_13_0.setRegister(0x0, s);
   LastWrite_13_1.setRegister(0x0, s);
   LastWrite_14_0.setRegister(0x0, s);
   LastWrite_14_1.setRegister(0x0, s);
   LastWrite_15_0.setRegister(0x0, s);
   LastWrite_15_1.setRegister(0x0, s);
   LastWrite_16_0.setRegister(0x0, s);
   LastWrite_16_1.setRegister(0x0, s);
   LastWrite_17_0.setRegister(0x0, s);
   LastWrite_17_1.setRegister(0x0, s);
   LastWrite_18_0.setRegister(0x0, s);
   LastWrite_18_1.setRegister(0x0, s);
   LastWrite_19_0.setRegister(0x0, s);
   LastWrite_19_1.setRegister(0x0, s);
   LastWrite_20_0.setRegister(0x0, s);
   LastWrite_20_1.setRegister(0x0, s);
   LastWrite_21_0.setRegister(0x0, s);
   LastWrite_21_1.setRegister(0x0, s);
   LastWrite_22_0.setRegister(0x0, s);
   LastWrite_22_1.setRegister(0x0, s);
   LastWrite_23_0.setRegister(0x0, s);
   LastWrite_23_1.setRegister(0x0, s);
   LastWrite_24_0.setRegister(0x0, s);
   LastWrite_24_1.setRegister(0x0, s);
   LastWrite_25_0.setRegister(0x0, s);
   LastWrite_25_1.setRegister(0x0, s);
   LastWrite_26_0.setRegister(0x0, s);
   LastWrite_26_1.setRegister(0x0, s);
   LastWrite_27_0.setRegister(0x0, s);
   LastWrite_27_1.setRegister(0x0, s);
   LastWrite_28_0.setRegister(0x0, s);
   LastWrite_28_1.setRegister(0x0, s);
   LastWrite_29_0.setRegister(0x0, s);
   LastWrite_29_1.setRegister(0x0, s);
   LastWrite_30_0.setRegister(0x0, s);
   LastWrite_30_1.setRegister(0x0, s);
   LastWrite_31_0.setRegister(0x0, s);
   LastWrite_31_1.setRegister(0x0, s);
   AOWaveformGeneration.setRegister(0x0, s);
   AOSelect.setRegister(0x0, s);
   G0G1_Select.setRegister(0x0, s);
   ELCSet.setRegister(0x0, s);
   ELCStatus.setRegister(0x0, s);
   ELCAck.setRegister(0x0, s);
}

void t6723::_initialize(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   //----------------------------------------
   // set register maps of all registers
   //----------------------------------------
   SerialCommand.setRegisterMap(this);
   Initialization.setRegisterMap(this);
   StatusReg.setRegisterMap(this);
   AOCalChanSel.setRegisterMap(this);
   ADCCommand.setRegisterMap(this);
   ADCStatus.setRegisterMap(this);
   ADCConversionData16.setRegisterMap(this);
   AOMisc.setRegisterMap(this);
   AOChanCount.setRegisterMap(this);
   DACFIFOFlags.setRegisterMap(this);
   FIFOData.setRegisterMap(this);
   DACDirty.setRegisterMap(this);
   DACLastWriteBank.setRegisterMap(this);
   FPGAVersion.setRegisterMap(this);
   FPGACheck.setRegisterMap(this);
   DirectData_00.setRegisterMap(this);
   DirectData_01.setRegisterMap(this);
   DirectData_02.setRegisterMap(this);
   DirectData_03.setRegisterMap(this);
   DirectData_04.setRegisterMap(this);
   DirectData_05.setRegisterMap(this);
   DirectData_06.setRegisterMap(this);
   DirectData_07.setRegisterMap(this);
   DirectData_08.setRegisterMap(this);
   DirectData_09.setRegisterMap(this);
   DirectData_10.setRegisterMap(this);
   DirectData_11.setRegisterMap(this);
   DirectData_12.setRegisterMap(this);
   DirectData_13.setRegisterMap(this);
   DirectData_14.setRegisterMap(this);
   DirectData_15.setRegisterMap(this);
   DirectData_16.setRegisterMap(this);
   DirectData_17.setRegisterMap(this);
   DirectData_18.setRegisterMap(this);
   DirectData_19.setRegisterMap(this);
   DirectData_20.setRegisterMap(this);
   DirectData_21.setRegisterMap(this);
   DirectData_22.setRegisterMap(this);
   DirectData_23.setRegisterMap(this);
   DirectData_24.setRegisterMap(this);
   DirectData_25.setRegisterMap(this);
   DirectData_26.setRegisterMap(this);
   DirectData_27.setRegisterMap(this);
   DirectData_28.setRegisterMap(this);
   DirectData_29.setRegisterMap(this);
   DirectData_30.setRegisterMap(this);
   DirectData_31.setRegisterMap(this);
   Calibration_00.setRegisterMap(this);
   Calibration_01.setRegisterMap(this);
   Calibration_02.setRegisterMap(this);
   Calibration_03.setRegisterMap(this);
   Calibration_04.setRegisterMap(this);
   Calibration_05.setRegisterMap(this);
   Calibration_06.setRegisterMap(this);
   Calibration_07.setRegisterMap(this);
   Calibration_08.setRegisterMap(this);
   Calibration_09.setRegisterMap(this);
   Calibration_10.setRegisterMap(this);
   Calibration_11.setRegisterMap(this);
   Calibration_12.setRegisterMap(this);
   Calibration_13.setRegisterMap(this);
   Calibration_14.setRegisterMap(this);
   Calibration_15.setRegisterMap(this);
   Calibration_16.setRegisterMap(this);
   Calibration_17.setRegisterMap(this);
   Calibration_18.setRegisterMap(this);
   Calibration_19.setRegisterMap(this);
   Calibration_20.setRegisterMap(this);
   Calibration_21.setRegisterMap(this);
   Calibration_22.setRegisterMap(this);
   Calibration_23.setRegisterMap(this);
   Calibration_24.setRegisterMap(this);
   Calibration_25.setRegisterMap(this);
   Calibration_26.setRegisterMap(this);
   Calibration_27.setRegisterMap(this);
   Calibration_28.setRegisterMap(this);
   Calibration_29.setRegisterMap(this);
   Calibration_30.setRegisterMap(this);
   Calibration_31.setRegisterMap(this);
   LastWrite_00_0.setRegisterMap(this);
   LastWrite_00_1.setRegisterMap(this);
   LastWrite_01_0.setRegisterMap(this);
   LastWrite_01_1.setRegisterMap(this);
   LastWrite_02_0.setRegisterMap(this);
   LastWrite_02_1.setRegisterMap(this);
   LastWrite_03_0.setRegisterMap(this);
   LastWrite_03_1.setRegisterMap(this);
   LastWrite_04_0.setRegisterMap(this);
   LastWrite_04_1.setRegisterMap(this);
   LastWrite_05_0.setRegisterMap(this);
   LastWrite_05_1.setRegisterMap(this);
   LastWrite_06_0.setRegisterMap(this);
   LastWrite_06_1.setRegisterMap(this);
   LastWrite_07_0.setRegisterMap(this);
   LastWrite_07_1.setRegisterMap(this);
   LastWrite_08_0.setRegisterMap(this);
   LastWrite_08_1.setRegisterMap(this);
   LastWrite_09_0.setRegisterMap(this);
   LastWrite_09_1.setRegisterMap(this);
   LastWrite_10_0.setRegisterMap(this);
   LastWrite_10_1.setRegisterMap(this);
   LastWrite_11_0.setRegisterMap(this);
   LastWrite_11_1.setRegisterMap(this);
   LastWrite_12_0.setRegisterMap(this);
   LastWrite_12_1.setRegisterMap(this);
   LastWrite_13_0.setRegisterMap(this);
   LastWrite_13_1.setRegisterMap(this);
   LastWrite_14_0.setRegisterMap(this);
   LastWrite_14_1.setRegisterMap(this);
   LastWrite_15_0.setRegisterMap(this);
   LastWrite_15_1.setRegisterMap(this);
   LastWrite_16_0.setRegisterMap(this);
   LastWrite_16_1.setRegisterMap(this);
   LastWrite_17_0.setRegisterMap(this);
   LastWrite_17_1.setRegisterMap(this);
   LastWrite_18_0.setRegisterMap(this);
   LastWrite_18_1.setRegisterMap(this);
   LastWrite_19_0.setRegisterMap(this);
   LastWrite_19_1.setRegisterMap(this);
   LastWrite_20_0.setRegisterMap(this);
   LastWrite_20_1.setRegisterMap(this);
   LastWrite_21_0.setRegisterMap(this);
   LastWrite_21_1.setRegisterMap(this);
   LastWrite_22_0.setRegisterMap(this);
   LastWrite_22_1.setRegisterMap(this);
   LastWrite_23_0.setRegisterMap(this);
   LastWrite_23_1.setRegisterMap(this);
   LastWrite_24_0.setRegisterMap(this);
   LastWrite_24_1.setRegisterMap(this);
   LastWrite_25_0.setRegisterMap(this);
   LastWrite_25_1.setRegisterMap(this);
   LastWrite_26_0.setRegisterMap(this);
   LastWrite_26_1.setRegisterMap(this);
   LastWrite_27_0.setRegisterMap(this);
   LastWrite_27_1.setRegisterMap(this);
   LastWrite_28_0.setRegisterMap(this);
   LastWrite_28_1.setRegisterMap(this);
   LastWrite_29_0.setRegisterMap(this);
   LastWrite_29_1.setRegisterMap(this);
   LastWrite_30_0.setRegisterMap(this);
   LastWrite_30_1.setRegisterMap(this);
   LastWrite_31_0.setRegisterMap(this);
   LastWrite_31_1.setRegisterMap(this);
   AOWaveformGeneration.setRegisterMap(this);
   AOSelect.setRegisterMap(this);
   G0G1_Select.setRegisterMap(this);
   ELCSet.setRegisterMap(this);
   ELCStatus.setRegisterMap(this);
   ELCAck.setRegisterMap(this);

   reset(s);
}

t6723::~t6723()
{
}



// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

